#!/usr/bin/env bash
set -euo pipefail
#
# Generated by tack export v1.0.0
# Playbook:   setup.yaml
# Host:       web01
# WARNING: facts not gathered; fact references may be unresolved
#
# This is a SNAPSHOT. Re-export if playbook, inventory, or target facts change.
#
TACK_CHANGED=0
TACK_FAILED=0
TACK_CURRENT_TASK=""
on_exit() {
  local ec=$?
  if [[ $ec -ne 0 ]]; then
    echo "tack-export: FAILED on task: ${TACK_CURRENT_TASK}" >&2
  fi
  echo "tack-export: summary: changed=${TACK_CHANGED} failed=${TACK_FAILED}" >&2
  exit $ec
}
trap on_exit EXIT

# SKIPPED (when false): role == 'cache'

# === TASK: Install web packages === (tags: packages)
TACK_CURRENT_TASK='Install web packages'
DEBIAN_FRONTEND=noninteractive apt-get update -qq
if ! dpkg-query -W -f='${Status}' 'nginx' 2>/dev/null | grep -q 'install ok installed'; then
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --install-recommends 'nginx'
  TACK_CHANGED=$((TACK_CHANGED+1))
fi
if ! dpkg-query -W -f='${Status}' 'curl' 2>/dev/null | grep -q 'install ok installed'; then
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --install-recommends 'curl'
  TACK_CHANGED=$((TACK_CHANGED+1))
fi


# === TASK: Create the application user === (tags: users)
TACK_CURRENT_TASK='Create the application user'
if ! getent passwd 'appsvc' >/dev/null 2>&1; then
  useradd -r -s '/usr/sbin/nologin' 'appsvc'
  TACK_CHANGED=$((TACK_CHANGED+1))
else
  usermod -s '/usr/sbin/nologin' 'appsvc'
  TACK_CHANGED=$((TACK_CHANGED+1))
fi


# === TASK: Create the document root === (tags: files)
TACK_CURRENT_TASK='Create the document root'
if [ ! -d '/var/www/app' ]; then
  mkdir -p '/var/www/app'
  TACK_CHANGED=$((TACK_CHANGED+1))
fi
chmod 755 '/var/www/app'
chown 'appsvc' '/var/www/app'


# === TASK: Drop a landing page === (tags: files)
TACK_CURRENT_TASK='Drop a landing page'
cat > '/var/www/app/index.html.tack.tmp' <<'TACK_EOF'
<h1>Deployed by tack</h1>

TACK_EOF
if ! diff -q '/var/www/app/index.html' '/var/www/app/index.html.tack.tmp' >/dev/null 2>&1; then
  mv '/var/www/app/index.html.tack.tmp' '/var/www/app/index.html'
  TACK_CHANGED=$((TACK_CHANGED+1))
else
  rm -f '/var/www/app/index.html.tack.tmp'
fi
chmod 644 '/var/www/app/index.html'


# === TASK: Enable and start nginx === (tags: services)
TACK_CURRENT_TASK='Enable and start nginx'
if ! systemctl is-active --quiet 'nginx.service'; then
  systemctl start 'nginx.service'
  TACK_CHANGED=$((TACK_CHANGED+1))
fi
if ! systemctl is-enabled --quiet 'nginx.service'; then
  systemctl enable 'nginx.service'
  TACK_CHANGED=$((TACK_CHANGED+1))
fi

