package export

import (
	"fmt"
	"sort"
	"strings"
)

// renderBanner produces the script header: shebang, set -euo pipefail, banner comments,
// counter declarations, and trap.
func (c *Compiler) renderBanner(host string) string {
	var sb strings.Builder

	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("set -euo pipefail\n")
	sb.WriteString("#\n")
	sb.WriteString(fmt.Sprintf("# Generated by tack export %s\n", c.Opts.Version))
	sb.WriteString(fmt.Sprintf("# Playbook:   %s\n", c.Opts.PlaybookPath))
	sb.WriteString(fmt.Sprintf("# Host:       %s\n", host))
	if !c.Opts.NoBannerTimestamp && c.Opts.Timestamp != "" {
		sb.WriteString(fmt.Sprintf("# Exported:   %s\n", c.Opts.Timestamp))
	}

	// Frozen facts
	if len(c.facts) > 0 {
		sb.WriteString(fmt.Sprintf("# Facts:      %s\n", formatFactsSummary(c.facts)))
	} else if c.Opts.NoFacts {
		sb.WriteString("# WARNING: facts not gathered; fact references may be unresolved\n")
	}

	sb.WriteString("#\n")
	sb.WriteString("# This is a SNAPSHOT. Re-export if playbook, inventory, or target facts change.\n")
	sb.WriteString("#\n")

	// Vault warning
	if c.VaultUsed {
		sb.WriteString("# WARNING: This script contains values decrypted from vault.\n")
		sb.WriteString("# Treat this file as SECRET and do not commit to version control.\n")
		sb.WriteString("#\n")
	}

	// Counters and trap
	sb.WriteString("TACK_CHANGED=0\n")
	sb.WriteString("TACK_FAILED=0\n")
	sb.WriteString("TACK_CURRENT_TASK=\"\"\n")
	sb.WriteString("on_exit() {\n")
	sb.WriteString("  local ec=$?\n")
	sb.WriteString("  if [[ $ec -ne 0 ]]; then\n")
	sb.WriteString("    echo \"tack-export: FAILED on task: ${TACK_CURRENT_TASK}\" >&2\n")
	sb.WriteString("  fi\n")
	sb.WriteString("  echo \"tack-export: summary: changed=${TACK_CHANGED} failed=${TACK_FAILED}\" >&2\n")
	sb.WriteString("  exit $ec\n")
	sb.WriteString("}\n")
	sb.WriteString("trap on_exit EXIT\n")

	return sb.String()
}

// formatFactsSummary renders facts as a sorted key=value line, skipping long values.
func formatFactsSummary(facts map[string]any) string {
	keys := make([]string, 0, len(facts))
	for k := range facts {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var parts []string
	for _, k := range keys {
		v := fmt.Sprintf("%v", facts[k])
		if len(v) > 200 {
			continue
		}
		// Skip complex types
		switch facts[k].(type) {
		case map[string]any, map[string]string, []any:
			continue
		}
		parts = append(parts, fmt.Sprintf("%s=%s", k, v))
	}
	return strings.Join(parts, " ")
}
