// Package generate captures live system state and produces playbook YAML.
package generate

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/eugenetaranov/bolt/internal/connector"
	"github.com/eugenetaranov/bolt/pkg/facts"
)

// WarnWriter is where warning messages are written (defaults to stderr).
var WarnWriter io.Writer = os.Stderr

// TaskDef represents a single task to be rendered into a playbook.
type TaskDef struct {
	Name   string
	Module string
	Params map[string]any
	Loop   []string // if non-empty, emit loop syntax and collapse into one task
}

// Collector reads live state for specific named resources.
type Collector interface {
	Collect(ctx context.Context, conn connector.Connector, names []string, f map[string]any) ([]TaskDef, error)
}

// Options configures what resources to capture.
type Options struct {
	Packages   []string
	Files      []string
	Services   []string
	Users      []string
	Hosts      []string
	Connection string
	Output     string // file path, empty for stdout
}

// Generate connects to the target, gathers facts, runs collectors, and writes playbook YAML.
func Generate(ctx context.Context, conn connector.Connector, opts Options) error {
	if err := conn.Connect(ctx); err != nil {
		return fmt.Errorf("failed to connect: %w", err)
	}
	defer conn.Close()

	// Gather facts
	f, err := facts.Gather(ctx, conn)
	if err != nil {
		return fmt.Errorf("failed to gather facts: %w", err)
	}

	var allTasks []TaskDef

	// Run requested collectors
	if len(opts.Packages) > 0 {
		tasks, err := (&PackageCollector{}).Collect(ctx, conn, opts.Packages, f)
		if err != nil {
			return fmt.Errorf("package collection failed: %w", err)
		}
		allTasks = append(allTasks, tasks...)
	}

	if len(opts.Files) > 0 {
		tasks, err := (&FileCollector{}).Collect(ctx, conn, opts.Files, f)
		if err != nil {
			return fmt.Errorf("file collection failed: %w", err)
		}
		allTasks = append(allTasks, tasks...)
	}

	if len(opts.Services) > 0 {
		tasks, err := (&ServiceCollector{}).Collect(ctx, conn, opts.Services, f)
		if err != nil {
			return fmt.Errorf("service collection failed: %w", err)
		}
		allTasks = append(allTasks, tasks...)
	}

	if len(opts.Users) > 0 {
		tasks, err := (&UserCollector{}).Collect(ctx, conn, opts.Users, f)
		if err != nil {
			return fmt.Errorf("user collection failed: %w", err)
		}
		allTasks = append(allTasks, tasks...)
	}

	if len(allTasks) == 0 {
		return fmt.Errorf("no resources captured")
	}

	// Marshal to YAML
	out, err := marshalPlaybook(opts, allTasks)
	if err != nil {
		return fmt.Errorf("failed to marshal playbook: %w", err)
	}

	// Write output
	if opts.Output != "" {
		return os.WriteFile(opts.Output, out, 0644)
	}
	_, err = os.Stdout.Write(out)
	return err
}

// marshalPlaybook builds a playbook YAML document from task definitions.
func marshalPlaybook(opts Options, tasks []TaskDef) ([]byte, error) {
	// Build the play as an ordered map
	play := &yaml.Node{Kind: yaml.MappingNode}

	// name
	play.Content = append(play.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "name"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "Generated playbook"},
	)

	// hosts
	hosts := opts.Hosts
	if len(hosts) == 0 {
		hosts = []string{"localhost"}
	}
	hostsNode := &yaml.Node{Kind: yaml.SequenceNode}
	for _, h := range hosts {
		hostsNode.Content = append(hostsNode.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: h})
	}
	play.Content = append(play.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "hosts"},
		hostsNode,
	)

	// connection
	conn := opts.Connection
	if conn == "" {
		conn = "local"
	}
	play.Content = append(play.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "connection"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: conn},
	)

	// tasks
	tasksNode := &yaml.Node{Kind: yaml.SequenceNode}
	for _, t := range tasks {
		taskNode := buildTaskNode(t)
		tasksNode.Content = append(tasksNode.Content, taskNode)
	}
	play.Content = append(play.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "tasks"},
		tasksNode,
	)

	// Wrap in document
	doc := &yaml.Node{
		Kind: yaml.DocumentNode,
		Content: []*yaml.Node{
			play,
		},
		HeadComment: "Generated by: bolt generate",
	}

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return addBlankLinesBetweenTasks(buf.Bytes()), nil
}

// addBlankLinesBetweenTasks inserts a blank line before each "  - name:" task
// entry except the first one, since yaml.v3 doesn't support blank lines natively.
func addBlankLinesBetweenTasks(data []byte) []byte {
	lines := strings.Split(string(data), "\n")
	var out []string
	first := true
	for _, line := range lines {
		if strings.HasPrefix(line, "  - name:") {
			if !first {
				out = append(out, "")
			}
			first = false
		}
		out = append(out, line)
	}
	return []byte(strings.Join(out, "\n"))
}

// buildTaskNode creates a yaml.Node for a single TaskDef.
func buildTaskNode(t TaskDef) *yaml.Node {
	node := &yaml.Node{Kind: yaml.MappingNode}

	// name
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "name"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: t.Name},
	)

	// module params
	paramsNode := mapToNode(t.Params)
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: t.Module},
		paramsNode,
	)

	// loop
	if len(t.Loop) > 0 {
		loopNode := &yaml.Node{Kind: yaml.SequenceNode}
		for _, item := range t.Loop {
			loopNode.Content = append(loopNode.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Value: item})
		}
		node.Content = append(node.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "loop"},
			loopNode,
		)
	}

	return node
}

// mapToNode converts a map[string]any to a yaml.Node (MappingNode).
func mapToNode(m map[string]any) *yaml.Node {
	node := &yaml.Node{Kind: yaml.MappingNode}
	for k, v := range m {
		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: k}
		valNode := anyToNode(v)
		node.Content = append(node.Content, keyNode, valNode)
	}
	return node
}

// anyToNode converts an arbitrary value to a yaml.Node.
func anyToNode(v any) *yaml.Node {
	switch val := v.(type) {
	case string:
		node := &yaml.Node{Kind: yaml.ScalarNode, Value: val}
		// Use literal block style for multi-line content
		if strings.Contains(val, "\n") {
			node.Style = yaml.LiteralStyle
		}
		return node
	case bool:
		return &yaml.Node{Kind: yaml.ScalarNode, Value: fmt.Sprintf("%t", val), Tag: "!!bool"}
	case int:
		return &yaml.Node{Kind: yaml.ScalarNode, Value: fmt.Sprintf("%d", val), Tag: "!!int"}
	case int64:
		return &yaml.Node{Kind: yaml.ScalarNode, Value: fmt.Sprintf("%d", val), Tag: "!!int"}
	case float64:
		return &yaml.Node{Kind: yaml.ScalarNode, Value: fmt.Sprintf("%g", val), Tag: "!!float"}
	case []string:
		seq := &yaml.Node{Kind: yaml.SequenceNode}
		for _, s := range val {
			seq.Content = append(seq.Content, &yaml.Node{Kind: yaml.ScalarNode, Value: s})
		}
		return seq
	case []any:
		seq := &yaml.Node{Kind: yaml.SequenceNode}
		for _, item := range val {
			seq.Content = append(seq.Content, anyToNode(item))
		}
		return seq
	case map[string]any:
		return mapToNode(val)
	default:
		return &yaml.Node{Kind: yaml.ScalarNode, Value: fmt.Sprintf("%v", val)}
	}
}

// WriteOutput writes bytes to the given writer (used for testing).
func WriteOutput(w io.Writer, opts Options, tasks []TaskDef) error {
	out, err := marshalPlaybook(opts, tasks)
	if err != nil {
		return err
	}
	_, err = w.Write(out)
	return err
}
